#!/usr/bin/env python3
"""Crawl the Azure Microsoft Learn sitemaps and write data/corpus_sources.yaml.

    python scripts/build_corpus.py [per_service] [cap]

Defaults: 4 pages per service, capped at 1000 total. Re-run to refresh the list,
then `python -m ragpipe.ingest` to (re)build the search index.
"""
from __future__ import annotations

import sys

import yaml

from ragpipe.corpus import crawl_azure_sitemaps

OUTPUT = "data/corpus_sources.yaml"


def main() -> None:
    per_service = int(sys.argv[1]) if len(sys.argv) > 1 else 4
    cap = int(sys.argv[2]) if len(sys.argv) > 2 else 1000
    print(f"Crawling Azure sitemaps (per_service={per_service}, cap={cap})…")
    urls = crawl_azure_sitemaps(per_service=per_service, cap=cap)
    with open(OUTPUT, "w") as f:
        f.write("# Microsoft Learn (Azure) articles forming the RAG corpus.\n")
        f.write("# Generated by scripts/build_corpus.py — edit by re-running it.\n")
        yaml.safe_dump({"sources": urls}, f, default_flow_style=False, sort_keys=False)
    print(f"Wrote {len(urls)} URLs to {OUTPUT}")


if __name__ == "__main__":
    main()
